### ISSUE TITLE
Inconsistencies in approaches

### ISSUE THREAD

**Issue by sbmadhav** [areai51/fusion#60]
@areai51 , @vichu1988  - I see there are two different approaches take to component rendering - 
- The approach taken in 
    - [fusion/fusion/Banner.js](https://github.com/pagesource/fusion/blob/master/fusion/Banner.js) or
    - [fusion/fusion/Avatar.js](https://github.com/pagesource/fusion/blob/master/fusion/Avatar.js)
For simple components

VS

- The approach taken in 
    - [fusion/fusion/ToggleButton.js](https://github.com/pagesource/fusion/blob/master/fusion/ToggleButton.js) or
    - [fusion/fusion/Pagination.js](https://github.com/pagesource/fusion/blob/master/fusion/Pagination.js)
For components that require life cycle menthods

1. What is the recommended approach? 
2. Shouldn't all components include`constructor` and other life cycle methods by default so that it is easy to extend?
3. Do we have a template with which these components can be created for consistency within the project?

**Comment by areai51** [comment]
@sbmadhav yes that's intentional. Any component that doesn't need state should always be a sateless functional component [reference](https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc)
If you need state then use `extends PureComponent` so that shallow prop change are automatically added in [reference](https://codeburst.io/when-to-use-component-or-purecomponent-a60cfad01a81). 
Ideally we should never have to use `extends Component` but if we do come across a scenario where we have to mutate stuff or something then use `extends Component` but then it should have a `ShouldComponentUpdate()`

**Comment by sbmadhav** [comment]
Okay, got it. Thanks @areai51 !
